### PR TITLE
Updates Passwordable Behavior to allow a max length of 50

### PR DESCRIPTION
**Pull request by jtyost2**
Default min password length is not changed

### CODE REVIEW

**Comment by dereuromark** [comment]
Sure a good idea!
But since you pointed out that people should be able to use pass phrases that can easily extend the 20 chars, it is probably best to globally up the limit:
https://github.com/dereuromark/cakephp-tools/commit/d031aec598500d11258334ed3413ed37900e1d96

Closing then. Thank you for the valueable input, even if it could have been provided in a different and less shouting way.

**Comment by jtyost2** [comment]
@dereuromark Wasn't trying to shout, just wondering why. I wasn't sure if you wanted a PR against the tools repo offered or else I would have done that.

**Comment by dereuromark** [comment]
The `seriously why?` part of the twitter post sounded like it.
Anyway, glad we figured it out.

**Comment by dereuromark** [comment]
PS: server updated

**Comment by jtyost2** [comment]
Sorry about that, I'll try to remember that in future internet dealings. Thank you for listening especially if I came across as shouty.

**Pull request closed without merging**
