### PR TITLE
problem 1.

### PR DESCRIPTION
**Pull request by renardrouge**
a user who had joined the event can not edit his attendance entry.
(Submit gave "You can only have one attendance entry per event")

changes made to repair

    src/Model/Table/AttendeesTable.php
        remove 'isUnique' validation from 'event_id' => array(

    src/Controller/AttendanceController.php
        edit function()
        // $this->render('add');
        $this->render('edit'); // 2015-01-25, LAD

    src/Template/Attendance/edit.ctp
        (copied from add.ctp and slightly modified)

problem 2.
admin attendees edit produces this error
Error: Table "App\Model\Table\AttendeesTable" is not associated with "User"

changes made to repair

    use "cake bake all attendees" as a model to change the
    AttendeesController.php edit() function,

### CODE REVIEW

**Comment by dereuromark** [comment]
Well, the user should only ever have a single event to work with (the current upcoming cakefest).
But yeah, the validation needs to be relaxed.

You seem to have a lot of noise in this PR though.

**Comment by renardrouge** [comment]
Hi Mark !
"You seem to have a lot of noise in this PR though." ???    meaning ?  too verbose in description or too much back and forth previously ?  I am just becoming familiar with github.  PRs are foreign to me. (plus I do not find the github interface to be terribly intuitive).  So, did I finally complete the PR process ?

**Comment by dereuromark** [comment]
You closed it (by accident?).

Well noise in the sense of "unnecessary change" along with the rest of the change you actually wanted to introduce. You must be careful when committing to not commit too much unrelated stuff :)

**Comment by renardrouge** [comment]
Yahh, closed by accident.   As I said before, not terribly intuitive for a novice.  So, what part was unrelated ?

**Comment by dereuromark** [comment]
25 files changes?
spaces instead of tabs introduce noise, as well.
This project, as outlined in the readme, uses the *sane* PSR-2-R (alias CakePHP2.x) CS.

**Comment by renardrouge** [comment]
If you mean all of the image files that changed, I think that was a result of a composer update --dev after my git clone.
To my knowledge, I only explicitly touched 4 files.   I did the composer update due to missing /vendor.
How should I do this type of operation in the future ?

**Comment by dereuromark** [comment]
That unique thing was a core bug, I fixed it via shim for now: https://github.com/dereuromark/cakephp-tools/commit/3738fda722e5e3d16c4555917fe08ede76e4106d
Please "composer update"

Dunno, just be careful about the changes, maybe check the diff first before pushing.

**Comment by renardrouge** [comment]
so should i .gitignore anything that i did not touch in the future ?  does your "core bug" fix remove the necessity of my changes ?

**Comment by dereuromark** [comment]
I am sure it did. Please confirm.

**Comment by renardrouge** [comment]
how about the edit.ctp fix ?

**Comment by dereuromark** [comment]
What about it?
All that was needed was that the validation works.

**Comment by renardrouge** [comment]
but edit.ctp did not exist previously ?   just add.ctp.

**Comment by dereuromark** [comment]
add = edit in this case.

**Comment by renardrouge** [comment]
ok, i will try.   will report in later.  i have a meeting to attend that goes for 4 1/2 hours.

**Comment by renardrouge** [comment]
I did a new git clone https://github.com/dereuromark/cakefest.git, followed by composer update --dev.
Problem 1 is solved.
Problem 2 still exists, exactly as reported previously.   My fix makes  problem 2 go away.

**Comment by dereuromark** [comment]
Did you bake? You are not supposed to re-bake existing templates. Baking was only useful for the initial HTML layout.

**Comment by renardrouge** [comment]
I did not bake.    clone, composer update --dev, create app_local.php.  that is all.

**Comment by renardrouge** [comment]
i make it 3:30 your time.   do you ever sleep  :-)

**Comment by renardrouge** [comment]
my previous bake model was generated soley from the database definitions.  i did that so i could see what code was generated, and then compared with your code in a separate app.

**Comment by renardrouge** [comment]
have you fired up cakefest locally and then done the "admin"  "attendees" "edit" ?  i would expect you to see the same problem.   if not, we should look at outside differences ?  i am running a fairley recent xampp apache server on an up to date windows 7 laptop, php 5.6.3.

**Comment by dereuromark** [comment]
You were right. Due to the space indentation and the huge diff, that one single change didn't really show in the diff. I fixed it.

**Pull request closed without merging**
